const projects = [
  {
    id: 1,
    name: 'Budget App',
    descriptionMobile: 'Budget App is not other app that allow us to add new payments to certain categories. You can add new categories and new payments to every category you just need to click on add new.',
    descriptionMobilePopup: 'Budget App is not other app that allow us to add new payments to certain categories.',
    descriptionDesktopPopUp: 'Budget App is not other app that allow us to add new payments to certain categories. You can add new categories and new payments to every category you just need to click on add new.',
    image: './mexico-transfer.png',
    technologies: ['Ruby on Rails', 'GitHub'],
    link: 'https://github.com/eri8-9/budget_app',
    demoLive: 'https://morning-journey-90954.herokuapp.com/',
  },
  {
    id: 2,
    name: 'Air Pollution',
    descriptionMobile: 'A web application where we are able to see the air pollution in each and everyone of the countries selected by the user. It contains data for every component.',
    descriptionMobilePopup: 'A web application where we are able to see the air pollution in each and everyone of the countries selected by the user.',
    descriptionDesktopPopUp: 'A web application where we are able to see the air pollution in each and everyone of the countries selected by the user. It contains data for every component.',
    image: './air-pollution.png',
    technologies: ['Html', 'React & Redux', 'Css'],
    link: 'https://github.com/eri8-9/air-pollution',
    demoLive: 'https://eri8-9.github.io/air-pollution/#/',
  },
  {
    id: 3,
    name: 'Catalog Of My Things',
    descriptionMobile: 'A simple application build with ruby where you can add books, movies, games, genres, labels, authors and sources.',
    descriptionMobilePopup: 'A simple application build with ruby where you can add books, movies, games, genres, labels, authors and sources.',
    descriptionDesktopPopUp: 'A simple application build with ruby where you can add books, movies, games, genres, labels, authors and sources. Everything works by the console in ruby.',
    image: './catalog.png',
    technologies: ['Ruby', 'Github'],
    link: 'https://github.com/eri8-9/Catalog_of_my_things',
    demoLive: 'https://github.com/eri8-9/Catalog_of_my_things',
  },
  {
    id: 4,
    name: 'Space Travelers',
    descriptionMobile: 'App where you can find spaceships from space-x. You can reserve every spaceship and their missions',
    descriptionMobilePopup: 'App where you can find spaceships from space-x. You can reserve every spaceship and their missions',
    descriptionDesktopPopUp: 'App where you can find spaceships from space-x. You can reserve every spaceship and their missions. Once selected a mission or rocket you can see your reservations on a table.',
    image: './space-travelers.png',
    technologies: ['React & Redux', 'Github'],
    link: 'https://github.com/eri8-9/Space-Travelers-Hub',
    demoLive: 'https://github.com/eri8-9/Space-Travelers-Hub',
  },
];

export default projects;